### PR TITLE
Remove storybook

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Removes StoryBook as it isn't being utilized by the team.

For discussion:
I think we can drop the documentation pages for:

[Api](https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/admin-docs-api-documentation--page)

[Schema](https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/forms-docs-form-builder-database-schema--page)

[Form Viewer JSON Specification](https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/forms-docs-form-viewer-json--page)

I don't think these pages provide much value at the moment and are bound to fall out of date

I converted a11y + System Architecture to converted to plain markdown

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by timarney** [comment]
For discussion:
I think we can drop the documentation pages for:

Api
https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/admin-docs-api-documentation--page
+ 
Schema
https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/forms-docs-form-builder-database-schema--page


I don't think this page provides much value in it's current form / current API users

a11y
https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/forms-docs-accessibility-report-for-forms-alpha--page

perhaps this page should be more "built-in" to the product so we can collect feedback

System Architecture
https://cds-snc.github.io/platform-forms-client/refs/pull/1911/merge/?path=/story/forms-docs-architecture--page

I'll update this to just Markdown

**Comment by timarney** [comment]
>  Path does not exist /home/runner/work/platform-forms-client/platform-forms-client/cypress/screenshots

@bryan-robitaille any idea why this happens with Cypress sometimes?

**Comment by bryan-robitaille** [comment]
@timarney in this case it looks like a package didn't get installed properly so cypress didn't even launch.  That's why it couldn't find the screenshots folder.  I know github was actions was having issues this afternoon.  I'll relaunch the action to see if it self heals or a sign of a bigger problem.
Screenshot 2023-04-17 at 4 11 10 PM

**Comment by bryan-robitaille** [comment]
Looks like there's an issue with the cypress workflow where sub-modules aren't being installed as part of the cache.  Will open a separate PR to fix.

**Review by bryan-robitaille — APPROVED** [review]
This will stop it from being rebuilt and deployed so we can safely merge it while the previous version remains available on GitHub pages.

**Pull request merged**
