### PR TITLE
refactor: NextJS App Router

### LINKED ISSUE #3117: NextJS App Router Conversion
Updates GCForms to leverage the latest version of NextJS and the new App Router features.

Initial items to complete:
- [x] Convert Pages to new app router segments and transform GetServerSideProps to Server Side Components.
- [x] Convert APIs to new app router routes and new NextResponse object
- [x] Create base and segmented Layouts
- [x] Mark client components with "use client"
- [x] Create base global server components for Static Pages
- [x] Remove next-i18next and create new client and server instances of react-i18next
- [x] Rewrite middleware of API routes to handle new NextRequest and NextResponse objects
- [x] Implement new Content Security Policy generative module as previous version relied on intercepting NextJS scripts.
- [ ] Test application end to end
- [x] Update Jest tests reflect new layout
- [x] Update Cypress tests 

Items tagged on due to errors / issues encountered during the migration:
- [x] Upgrade Next-Auth to experimental version 5 due to incompatibility with new NextRequest and NextResponse objects.
- [x] Disable mmmagic.  The package errors when trying to be included in the NextJS build process.  Package has not been updated in 5 years.  Need to find a replacement when we broaden the ability to accept file attachements in forms
- [x] Cypress not rendering Client Components properly.  Somehow layouts are also being captured.
- [ ] Unsupported Browser and Javascript Disabled pages can not be routed to with current logic.  App router will respond 404 because paths are not part of App folder and are currently in Public
- [x] Most buttons that redirect do not include the locale/language in the url and throw errors when NextJS prefetches the link.
- [ ] useEffects and other hooks that list session as a dependency are rendering way too many times because the 'expiry' property on the Session is updated on every session check call to the server.  We need to parse out the values that are of importance is possible for the dependency to remove unnecessary  rerenders.
- [ ] <Head> used by some components to dynamically change the title of the page.  This is not suppored in App Router.  Need to find a way to work around this.  Current code commented out for now.

### PR DESCRIPTION
**Pull request by bryan-robitaille**
# Summary | Résumé

cypress component jest

Updates project to leverage NextJS 14 features of the App Router.

- Next-auth is functional and under `/app`
- i18n has different initializers based on Server vs client components
- Middleware handles redirecting and checking for locale. 
- The locale `en | fr` will always be prefixed to the pathname except for the language switcher found at `/`.
- The language selection page will check for existing language preferences and set language order accordingly.
- Language detection built in to serverTranslations to remove requirement to pass expected language
- Custom detector added to server side rendering language detection  for useTranslations to avoid hydration mismatches
- Content Security Policy securely applied to pages under app router.  Modified from using hashes to nonces.
- API routes modified to leverage to named method exports. 
- Middleware function for API routes modified to handle to NextRequest and NextResponse types.
- Previous page layouts have been converted to route 'layout.tsx' for nested layouts.
- Only a handle of components have currently been converted to pure Server Components.  Ongoing work required by dev team to identify potential for conversion and common layout patterns.

- Cypress component tests do not work with app router.  Additional layout components like Footer are being rendered even though they are not being referenced..  Will need to address in the future.

closes #3117

### CODE REVIEW

**Comment by timarney** [comment]
Todo:
- [ ] fix the left nav to highlight the current page (form builder, my forms , admin)

**Comment by timarney** [comment]
Visiting a form I'm getting an error

Pretty sure I've seen this error before in CI --- 

http://localhost:3000/en/id/cllnw6myq0000e5pqyfl2ota4

but might be a fresh error given the locale updates

Screenshot 2023-08-23 at 12 25 16 PM

**Comment by bryan-robitaille** [comment]
Probably a fresh error.
Lol the one thing I didn't test....

**Comment by timarney** [comment]
> Lol the one thing I didn't test....

Who needs the actual form output ;)

**Comment by thiessenp-cds** [comment]
> Visiting a form I'm getting an error
> 
> Pretty sure I've seen this error before in CI ---
> 
> http://localhost:3000/en/id/cllnw6myq0000e5pqyfl2ota4
> 
> but might be a fresh error given the locale updates
> 
> Screenshot 2023-08-23 at 12 25 16 PM

I get the same error. (create a new form, publish it, then try to view it) But that's the only error I've seen so far

**Comment by bryan-robitaille** [comment]
@timarney @thiessenp-cds 
Thanks for flagging.  Those bugs should now be fixed.

**Comment by timarney** [comment]
Confirmed the form output is now working as expected 🎈 

A few items from here to look at https://github.com/cds-snc/platform-forms-client/pull/2583#issuecomment-1690258329

+ the conflicts from https://github.com/cds-snc/platform-forms-client/pull/2587

Looking solid.

**Comment by timarney** [comment]
Landing page issue:

**Staging**
Screenshot 2023-09-08 at 8 00 56 AM

**This branch**
- Scroll issue + GC forms shows in EN for "en and FR " for the title
Screenshot 2023-09-08 at 8 01 19 AM

**Comment by timarney** [comment]
Found some issues with the landing page --- outside of that seems to be working as expected 🎈 

Thinking at this point we should outline next steps here re: plan to merge to staging etc... + testing to a wider user group to ensure things are functioning 1:1 (for the most part) with the existing.

**Comment by bryan-robitaille** [comment]
> Landing page issue:

> https://forms-staging.cdssandbox.xyz/fr --- lands on landing page with FR logo

> local 404s

> https://forms-staging.cdssandbox.xyz/en -- redirects

> local 404s

100% - just noticed that I had that as an unchecked todo item earlier in the convo.

The Styling your seeing though might be a local cache issue as that was fixed.

The review environment is showing it correctly: https://ocohzq75nhmfgavuj6jz2fq3my0pdjpc.lambda-url.ca-central-1.on.aws/

**Comment by timarney** [comment]
Yes the styling  scroll issue on the landing page is a non issue -- cleared on my local

**Comment by timarney** [comment]
404's don't seem to work as they do on staging

https://forms-staging.cdssandbox.xyz/en/auth/loginf

For http://localhost:3000/en/edd I'm seeing just a white screen Page not found as the title --- not sure what page it was but I did hit a 404 local with the "not found" component but it was dropping the header and footer.

**Comment by timarney** [comment]
@bryan-robitaille --- re landing page when the cookie has FR value --- do you end up seeing the error ?

Text mistmatch server --- only seems to happen for FR.

Screenshot 2023-09-08 at 9 00 17 AM

**Comment by bryan-robitaille** [comment]
> 404's don't seem to work as they do on staging
> 
> https://forms-staging.cdssandbox.xyz/en/auth/loginf
> 
> For http://localhost:3000/en/edd I'm seeing just a white screen Page not found as the title http://localhost:3000/en/404
> 
> --- not sure what page it was but I did hit a 404 local with the "not found" component but it was dropping the header and footer.

I'll add the header and footer.  For some reason I didn't think they existed on the 404 page.

**Comment by bryan-robitaille** [comment]
> re landing page when the cookie has FR value --- do you end up seeing the error ?
Interesting.. that should have been fixed but I'll look at it again.

**Pull request merged**
