### PR TITLE
fix: add noindex meta tag in Staging on all pages including root index

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

- Attempting to fix `noindex` meta tag not being included on root index page

### CODE REVIEW

**Comment by timarney** [comment]
Thoughts on generating a robots.txt file?

https://mmazzarolo.com/blog/2021-04-27-nextjs-robots-txt/#generating-a-robotstxt-in-the-build-process

**Comment by craigzour** [comment]
> Thoughts on generating a robots.txt file?
> 
> Can alter for prod
> 
> ```
> const robotsTxt =
>     process.env.VERCEL_ENV === "production"
>       ? crawlableRobotsTxt
>       : uncrawlableRobotsTxt;
> ```
> 
> https://mmazzarolo.com/blog/2021-04-27-nextjs-robots-txt/#generating-a-robotstxt-in-the-build-process

I used the `noindex` meta tag approach because we want to make sure we are not included in search results. 

According to https://aioseo.com/docs/when-to-use-noindex-or-the-robots-txt/ this is the right solution for what we are trying to achieve.

`So if you want content not to be included in search results, then use NOINDEX. If you want to stop search engines crawling a directory on your server because it contains nothing they need to see, then use “Disallow” directive in your robots.txt file.`

**Review by thiessenp-cds — COMMENTED** [review]
Oh interesting, so it looks like it was a context problem. 
Nice, LGTM :) but I'll leave the PR open for @timarney to look at as well

**Review by timarney — APPROVED** [review]

**Comment by craigzour** [comment]
Also got confirmation in the Google documentation in the intro of https://developers.google.com/search/docs/crawling-indexing/robots/intro that the `robots.txt` file would not keep us out of search results. cc @thiessenp-cds @timarney

**Pull request merged**
