### PR TITLE
refactor: update max with for static pages

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

- Updates the max width for 

```
/terms-of-use
/sla
/terms-and-conditions.tsx
```

- Updates padding . margins for the "page container" so things line up with the FIP across breakpoints

# Test instructions | Instructions pour tester la modification
- Visit pages listed above ... note they no longer span the full width.

<hr>

- Test content pages at smaller breakpoints to ensure alignment 
- Test public facing form output across the same breakpoints

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

Are there any related issues or tangent features you consider out of scope for
this issue that could be addressed in the future? If so please create issues and provide
links in this section

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by connorscarolyns** [comment]
Some of the break points are causing misalignment with the header.
image

**Review by thiessenp-cds — COMMENTED** [review]
I noticed the same behaviour for small screens that Carolyn pointed out. I guess the header could match the break points but that may be a bigger change / require lots of testing across the form-builder?
Perhaps this is good as is and update the header in a future PR?

Screenshot 2023-09-27 at 10 01 36 AM

**Comment by timarney** [comment]
I'll play around with it ... 

Part is controlled by the older global css vs the header has been updated to use more on the Tailwind side.

**Comment by timarney** [comment]
@connorscarolyns @thiessenp-cds 

Pushed updates https://v2c76uybf3zkcktpavhcgyykm40qpbjz.lambda-url.ca-central-1.on.aws --- updates public facing form output as well.  What do you think?

**Review by dsamojlenko — APPROVED** [review]
Looks much better

**Review by thiessenp-cds — APPROVED** [review]
Nice work! LGTM :)
Screenshot 2023-09-27 at 1 23 28 PM
Screenshot 2023-09-27 at 1 22 06 PM


e.g.

**Pull request merged**
