### PR TITLE
fix:  Updates flags to be loaded from file

### PR DESCRIPTION
**Pull request by thiessenp-cds**
# Summary | Résumé

Updates flags to be loaded from file vs. manually maintaining the types list.

### CODE REVIEW

**Comment by timarney** [comment]
We end up without the typing here ... ends up as just a Record any

Screenshot 2024-09-27 at 2 30 38 PM

vs the current lists out the keys for us


Screenshot 2024-09-27 at 2 31 31 PM

The typed const is useful as we can do things like

```
const allowRepeatingSets = getFlag(FeatureFlags.repeatingSets);
```

Also typescript tells us if we try to use a flag that has been removed.

**Comment by timarney** [comment]
You might consider going the other way around ... update the places that use the json to grab the keys from the type.  Not sure if that will work but might be worth a shot.

**Comment by thiessenp-cds** [comment]
> We end up without the typing here ... ends up as just a Record any
> 
> Screenshot 2024-09-27 at 2 30 38 PM
> vs the current lists out the keys for us
> 
> Screenshot 2024-09-27 at 2 31 31 PM
> The typed const is useful as we can do things like
> 
> ```
> const allowRepeatingSets = getFlag(FeatureFlags.repeatingSets);
> ```
> 
> Also typescript tells us if we try to use a flag that has been removed.
> 
> With just a record we end up with no types Screenshot 2024-09-27 at 2 36 06 PM

I remember trying this last week and I was able to see the types, I think. But as for the error you see, I don't see that. Though the type info, yup I'm no longer seeing that. Will look into it.

**Comment by thiessenp-cds** [comment]
I don't think the JSON idea would work for dynamically creating a type definition that can be used in VSCode to show the available types.

**Pull request closed without merging**
