### PR TITLE
Additional GTM events and attributes for GA on forms life cycle

### PR DESCRIPTION
**Pull request by daine**
# Summary | Résumé

This PR adds some GTM code to help track events needed for 
- #2024 

Some significant changes:

- Add the ability to send a data attribute to the Button component

_**No UI Changes**_

# Test instructions | Instructions pour tester la modification
Testing these changes involve going into [GTM assistant](tagassistant.google.com) 

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

These only contain some code that is needed for event tracking; Majority of the work to complete the ticket resides inside GTM and Google Analytics

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Review by craigzour — COMMENTED** [review]
LGTM :) Will not approve myself as this is the first time I see some GTM stuff implemented.

**Review by thiessenp-cds — COMMENTED** [review]
Nice work, looks good to me :)

I'll leave the PR open encase anyone else has any comments

**Review by bryan-robitaille — COMMENTED** [review]
Nice work!  😃 

I noticed that `form-builder-share-email-attempt` was defined here but not being assigned to an active trigger in GTM?

A suggestion that we may want to use our own custom html attributes like you did with `data-share` instead of reusing `data-testid` as triggers in GTM.  There's a risk that the element changes and a developer may not be aware that the `data-testid` is driving Google Analytics.  A more descriptive attribute might help reduce that risk.

**Comment by daine** [comment]
Thanks @bryan-robitaille !

> I noticed that `form-builder-share-email-attempt` was defined here but not being assigned to an active trigger in GTM?

Yes! Main reason is I want to be able to access that action if needed for exploratory purposes. I don't want to have too much data on GA, but also I do want to track conversion from "share by email attempts" to actually hitting "send" on our "email the form file sharing feature".

> A suggestion that we may want to use our own custom html attributes like you did with `data-share` instead of reusing `data-testid` as triggers in GTM. There's a risk that the element changes and a developer may not be aware that the `data-testid` is driving Google Analytics. A more descriptive attribute might help reduce that risk.

Agree! And also I wonder if it's best to drop `testid` altogether and just assign `data-id` attributes? I thought about using a custom one but 1) I didn't want to add more code that could potentially be deleted because it's not used anywhere in the codebase and, 2) I'm certain that if we changed `data-testid` we would be changing tests as well and this could be a point where we can decide on best practices for attributes used for GA & tests

**Review by bryan-robitaille — APPROVED** [review]
Looks good 👍

**Review by bryan-robitaille — APPROVED** [review]
Thank you :)

**Pull request merged**
