### PR TITLE
Update to Next 13

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

⚠️  Updates to Next 13 and takes minimal migration steps to make existing code compatible. ⚠️ 

> Next.js 13 and the pages directory are stable and ready for production.

https://nextjs.org/blog/next-13

👉  Given the pages directory is stable we should be able to make the move now vs waiting and updating code to run in the `app` dir.

# Test instructions | Instructions pour tester la modification
- General click around

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [x] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by timarney** [comment]
@bryan-robitaille we'll need to discuss `how` and `when` to roll this out but - tests are passing things are up and running.  I haven't found any issues so far.

For now just wanted to see what might be involved.

**Comment by timarney** [comment]
Getting @dsamojlenko to test before I move this for further review.

**Comment by dsamojlenko** [comment]
LGTM
Everything seems to be working as normal after updating.

**Comment by timarney** [comment]
Updated to 13.2+

https://nextjs.org/blog/next-13-2

**Comment by timarney** [comment]
Will re-open once Github is back to normal

**Comment by bryan-robitaille** [comment]
Let's get this in after the next production release and we can look at taking advantage of some of the new features in future PR's.

**Comment by timarney** [comment]
API -
https://www.youtube.com/shorts/RXuOyR3yscM

**Review by craigzour — APPROVED** [review]
LGTM!

**Review by dsamojlenko — APPROVED** [review]

**Pull request merged**
