### PR TITLE
Moved over some of Nick's design updates from Storybook

### PR DESCRIPTION
**Pull request by fitore-cds**
# Summary | Résumé

- Moved over some of Nick's design updates from Storybook
- Lots more work remains :-)

### CODE REVIEW

**Review by bryan-robitaille — APPROVED** [review]
Going to approve because there's a lot of awesome work there.  The only comment I have is that the secondary button text is hardly visible anymore.  Need to look at in the near future.

**Review by nmakuch — APPROVED** [review]
Nice, sorry if this has caused more work :(

I can probably help you with some of this post demo

**Comment by nmakuch** [comment]
> Going to approve because there's a lot of awesome work there. The only comment I have is that the secondary button text is hardly visible anymore. Need to look at in the near future.

I can take a look into that for sure, noticed that when reviewing

**Comment by fitore-cds** [comment]
Thanks a lot @bryan-robitaille and @nmakuch - I made some fixes for the secondary button and added the "Heading" component (updated the JSON viewer docs). Let's hope this is good for the demo :-)

**Pull request merged**
