### PR TITLE
Add missing postgres-migrations dependency

### PR DESCRIPTION
**Pull request by jeffmaher-cds**
# Summary | Résumé

Was setting up this on a clean machine, and ran `yarn install` and `yarn dev`, but got the following pictured error:

postgres-migrations error

Seems like a dependency is missing, so I added it. `yarn dev` then was able to complete without error.

P.S. Credit goes to the Partnership Dev Prodev coding hour 😸 , as we were all trying to get this setup.

# Test instructions | Instructions pour tester la modification

1. `yarn install`
2. `yarn dev`

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

Question for the Forms dev team: Did I add the correct version of postgres-migrations? 

# Pull Request Checklist

Note: I had other setup programs and couldn't get it fully up and running. Could someone from the Forms dev team verify these things?

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Have you removed unnecessary lines such as `console.log` statements?
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by jeffmaher-cds** [comment]
@Moro-Code , @jeberhardt : You both looked like the most recent folks active in the repo, so sending your way! Let me know if you need anything else from me or if I should route somewhere else.

**Review by Moro-Code — CHANGES_REQUESTED** [review]
Hey Jeff. If you go to the migrations folder and your run yarn install that is where the dependency should be

**Comment by Moro-Code** [comment]
Closing this PR. Happy to answer any questions on slack @jeffmaher-cds

**Comment by jeffmaher-cds** [comment]
@Moro-Code : Thanks! Is this a documentation bug then? At what point would I run this in the setup?

**Pull request closed without merging**
