### PR TITLE
chore: Update branding options

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

- Adds FINTRAC & Canadian Nuclear Safety Commission branding

Test instructions | Instructions pour tester la modification
- Create a draft form
- Visit settings / branding + update branding to use  FINTRAC or Canadian Nuclear Safety Commission branding
- Visit `test` to check the branding on a form
- Flip en / fr toggle to check EN / FR logos

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by timarney** [comment]
Waiting on CNSC svgs

**Comment by jprince-cds** [comment]
CNSC_Signature_SVG_Colour_EN

We have been provided with the following SVG file for CNSC.

**Comment by timarney** [comment]
Screenshot 2023-07-28 at 3 12 56 PM

Screenshot 2023-07-28 at 3 13 13 PM

Updated -- back on hold for this one.

**Comment by jprince-cds** [comment]
CNSC_Signature_SVG_Colour_FR

@timarney Here is the French version for CNSC!

**Pull request merged**
