### PR TITLE
Fix/unsupported browser page

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

closes https://github.com/cds-snc/platform-forms-client/issues/2040

- Fixed broken "unsupported browser" page.
- Reworked and simplified code in `not-supported.tsx`.
- Changed the way we redirect a user to the "unsupported browser" page. Now using a `referer` URL parameter to transmit the URL the user was trying to access.

While working on the "unsupported browser" page I noticed that the `JSDisabled` one was not working as expected and also did not quite match the Figma design. I figured I could fix it here at the same time. I decided to switch from a NextJS page to an HTML static one since neither React or Next JS can work without Javascript enabled (that was also causing some issues with the previous `JSDisabled` page).

Screenshot 2023-05-09 at 2 38 05 PM
Screenshot 2023-05-09 at 2 37 25 PM

# Test instructions | Instructions pour tester la modification

For the "unsupported browser" page:

- Make sure you start your environment un production mode `yarn build && yarn start`
- Using Internet Explorer 11 (if you do not have access to it then just go in the `middleware.ts` file and replace line 7 with `if (true) {`)
- Try to access a form page (`http://localhost:3000/id/clh7uyzpk0001d9zld95huokw`). You should be redirected to the "unsupported browser" page

FYI: It can also be accessed manually: `http://localhost:3000/not-supported` or `http://localhost:3000/not-supported?referer=something` (there are two different states on that page).

For the "javascript disabled" page:

- Disable Javascript on your browser
- Try to access a page like `http://localhost:3000/admin/login`. You should be redirected to the "javascript disabled" page

FYI: It can also be accessed manually: `http://localhost:3000/javascript-disabled.html`.

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by craigzour** [comment]
@samsadasivan While the pull request is being reviewed. Would you be able to let me know if both pages (see screenshots in PR description) look ok/good for you? I am guessing we will then be able to update our Figma designs to reflect the latest changes.

**Review by thiessenp-cds — CHANGES_REQUESTED** [review]
Nice work! Seeing this brings back memories :) `<meta httpEquiv="Refresh..`

The No JavaScript part of the PR works great. Tested in Microsoft Edge Windows 10.
Screenshot 2023-05-09 at 4 04 55 PM

The IE 11 did not work for me in real IE 11 on Windows 10. It looks like an extra polyfill or something is needed. An error is stopping the page from loading
Screenshot 2023-05-09 at 3 59 22 PM

Also just for fun I tested in Microsoft Edge Windows 10 (+Chrome, Safari), it looks like there is a minor overflow issue
Screenshot 2023-05-09 at 4 02 32 PM

**Comment by craigzour** [comment]
@thiessenp-cds I fixed the overflow issue. 

About the IE 11 unable to load `not-supported` page. It does work in production mode only `yarn build && yarn start`. 
I remember us trying to make it work (with all the polyfill stuff) in dev mode at some point but gave up because it was not worth it. Am I right @bryan-robitaille ?

**Comment by bryan-robitaille** [comment]
> About the IE 11 unable to load `not-supported` page. It does work in production mode only `yarn build && yarn start`.

@craigzour I don't remember the exact issue but as long as the page loads in production mode `yarn build && yarn start` it's all the matters.

**Comment by craigzour** [comment]
> Possibly for another PR Tested with IE 7
> 
> With a browser that doesn't fall in line with our `"browserslist"` the JS will fail to load and won't reach the desired page.
> 
> Screenshot 2023-05-10 at 11 32 49 AM

Could be something to look into but the code that was written to handle IE 11 was specifically built for that version so I think the decision that was taken was just to ignore IE versions below 11

**Comment by timarney** [comment]
@bryan-robitaille -- prod build 

The JS blows up -- 

Screenshot 2023-05-10 at 11 57 11 AM

**Comment by craigzour** [comment]
> @bryan-robitaille -- prod build
> 
> The JS blows up --
> 
> Screenshot 2023-05-10 at 11 57 11 AM

If we want to handle older IE versions I think the best solution (to be tested) would be to go with a static HTML page like I did for the javascript disabled scenario.
@srtalbot @bryan-robitaille should we handle IE < 11 ?

**Review by thiessenp-cds — APPROVED** [review]
Nice, LGTM!

The IE 11 page loads as expected and meets the design. There is still a console error but I think that's unavoidable being an unsupported browser etc..

For IE 7 perhaps that could be a separate PR if we decide to try loading a modern app in that questionable browser :)

Screenshot 2023-05-10 at 12 05 56 PM

**Comment by timarney** [comment]
> If we want to handle older IE versions I think the best solution (to be tested) would be to go with a static HTML page like I did for the javascript disabled scenario.
@srtalbot @bryan-robitaille should we handle IE < 11 ?

Agree on the static page --- for sure there are old computers out there that will not support an OS / browser update and we should at least show a rendered page vs a totally broken one.

**Comment by craigzour** [comment]
> > If we want to handle older IE versions I think the best solution (to be tested) would be to go with a static HTML page like I did for the javascript disabled scenario.
> > @srtalbot @bryan-robitaille should we handle IE < 11 ?
> 
> Agree on the static page --- for sure there are old computers out there that will not support an OS / browser update and we should at least show a **rendered page** vs a totally broken one.

Will open a new issue and make a prototype with a static page.

**Comment by craigzour** [comment]
Opened issue https://github.com/cds-snc/platform-forms-client/issues/2081 for IE < 11

**Comment by craigzour** [comment]
@samsadasivan I am going to merge the pull request. Will you be able to update the Figma designs to reflect the two screenshots I attached to the pull request description?

**Pull request merged**
