### PR TITLE
refactor: default forms to "all" 

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Updates "forms" subnav to default highlight "all" as the selected sub nav item

**Before** 

The "all" sub nav highlighting happens "late" 

We know all will be highlighted so we can safely default to that item. 

# Test instructions | Instructions pour tester la modification

- Visit `/forms` note the sub nav highlights properly 
- Also visit the form builder as the Sub nav is also used there --- no updates but ensure it's working as current

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

Noting -- for accounts with Manage All Forms / a large amount of cards we're still seeing a small "blip" but this PR updates will cover most use cases.

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Review by thiessenp-cds — CHANGES_REQUESTED** [review]
The default state for All is working. But it looks like tabbing between the other "tabs", the past active "tab" is not having the active state removed. 
I didn't look into why this is happening. I can help out if you're busy?

This nav has gone through a lot of changes since it's initial design, it will probably need some refactoring eventually. Though it may not be the best time now.
Screenshot 2023-09-27 at 9 46 47 AM

**Comment by thiessenp-cds** [comment]
I added some small changes. One to fix the navigation and the second to announce the content change when navigation happens.

Notes:
- Cards have a mix of tabs and "pills" components. Future refactor to use only one - pill or tab. (currently it's just confusing)
- live-region used around cards container to announce changes, very verbose and not ideal

**Review by thiessenp-cds — APPROVED** [review]
Approving because I updated with the change I asked for. Though you may want to get another to also approve the changes

**Comment by timarney** [comment]
Thanks @thiessenp-cds will "approve" your commits and merge.

**Pull request merged**
