### PR TITLE
Link to manage forms from deactivate modal

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Fixes https://github.com/cds-snc/platform-forms-client/issues/2392

Adds link to manage forms when deactivating a user with published forms
Screenshot 2023-07-12 at 8 56 25 AM

# Test instructions | Instructions pour tester la modification

- With a user account that has published forms deactivate the the user account
- The warning should now link to manage forms

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Review by thiessenp-cds — COMMENTED** [review]
The code looks great. Testing the functionality, within the open dialog, the Tab key doesn't seem to tab between the dialog controls. Does that work for you?

**Comment by connorscarolyns** [comment]
Tabbing manually is not working well.

I was able to use voiceover to move through the modal. Could we add a bit more info to the alert so users of AT know it's an alert? 

role="alert" and aria-label="alert" 
Seems to give VoiceOver the context users need.

image

**Comment by thiessenp-cds** [comment]
> The code looks great. Testing the functionality, within the open dialog, the Tab key doesn't seem to tab between the dialog controls. Does that work for you?

The problem is caused by Radix UI doing "magix" to its sub elements. If the Dialog is moved outside the Radix UI dropdown menu the problem goes away. I'm working on the dropdown now so I can do this fix in that PR if it would help

**Comment by connorscarolyns** [comment]
That makes sense; if it's too much trouble, I'd rather have it working well outside the menu than in. We can leave the additional permissions in it, which should cause the same issues.

**Comment by timarney** [comment]
> The problem is caused by Radix UI doing "magix" to its sub elements. If the Dialog is moved outside the Radix UI dropdown menu the problem goes away. I'm working on the dropdown now so I can do this fix in that PR if it would help

Yes let's look to move the Dialog outside of this PR.

**Review by thiessenp-cds — APPROVED** [review]
Sounds good. LGTM :)

**Comment by connorscarolyns** [comment]
Did we add:

"Could we add a bit more info to the alert so users of AT know it's an alert?

role="alert" and aria-label="alert"
Seems to give VoiceOver the context users need."

**Pull request merged**
