### PR TITLE
feat: Upgrade to Next JS 15 + React 19

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Updates to  Next.js 15  and React 19

Preview 👉 https://fe5xi5g32slhirpnfz3zkw2vpy0tdafc.lambda-url.ca-central-1.on.aws/

### Testing

- [x] Test login / out / reset / re-send code
- [x] Test support form
- [x] Test contact form
- [x] Test request publishing 
- [x] Test invite a user to a form
- [x]  Test create / submit 
- [x] Test download responses
- [x] Test profile / security questions
- [x] Test account sign-up
- [x] Test admin - accounts, feature flags etc...
- [x] Check static pages
- [x] Test share

### Notes

**Helpful Next 15 notes:**
- https://nextjs.org/blog/next-15
- https://nextjs.org/blog/next-15#async-request-apis-breaking-change

**React 19 Notes:**
> A long-time complaint of how TypeScript and React work has been useRef. We’ve changed the types so that useRef now requires an argument. 

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#useref-requires-argument

### CODE REVIEW

**Comment by dsamojlenko** [comment]
Did a quick first-pass review, fixed a few things... noted a few things to dig deeper on.

**Comment by timarney** [comment]
@dsamojlenko 

FYI found this in the cod mod docs so good to know

```
Good to know: When this codemod identifies a spot that might require manual intervention, but we aren't able to determine the exact fix, it will add a comment or typecast to the code to inform the user that it needs to be manually updated. These comments are prefixed with @next/codemod, and typecasts are prefixed with UnsafeUnwrapped. Your build will error until these comments are explicitly removed. [Read more](https://nextjs.org/docs/messages/sync-dynamic-apis).
```

Will get the Notify one fixed up.

**Comment by timarney** [comment]
@dsamojlenko per the upgrade guide I create a getOriginSync it's noted here "[Temporary Synchronous Usage](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#temporary-synchronous-usage-1)"

Using that for the invite a user --- Jest tests are passing again.  We can re-visit but I think this is okay for now.

Commit
https://github.com/cds-snc/platform-forms-client/pull/4468/commits/3d19e52af41ef48137bcb2a7b05f8aed678347f8#diff-029739f7e42b59efa6548b29ff34d9cf4bf1ca451a902175313234687a0df03fR21

**Comment by Abi-Nada** [comment]
Tested the following:
Authentication:
- [ ] Sign In (2FA,"Know Your Responsibilities" Page)
- [ ] Sign Out
- [ ] Reset Password

Added form elements:
- [ ] Add Hint Text
- [ ] Set Autocomplete
- [ ] Set Character Limits
- [ ] Set Required Fields
- [ ] Remove / Duplicate / Move Elements

Logic:
- [ ] Add Exit Pages
- [ ] Rename / Move / Remove Pages
- [ ] Display Logic (Show-Hide Rules)
- [ ] Branching Logic (Routing Rules)

Language:
- [ ] Language Toggling
- [ ] Translation View
- [ ] Exported CSV for translations

Sharing/Publishing:
- [ ] Save a JSON
- [ ] Share a Form
- [ ] Open a Form File
- [ ] Preview Draft Form
- [ ] Publish Form

Fill out form:
- [ ] Fill Out Published Form
- [ ] Test Data Validation
- [ ] Toggle English and French
- [ ] Review Page / Confirmation Page

Responses:
- [ ] Get Responses by Email
- [ ] Download HTML Response
- [ ] Download CSV Responses
- [ ] Download JSON Responses
- [ ] Bulk Download
- [ ] Receipt File
- [ ] Sign Off on Responses
- [ ] Report a Problem with Responses
- [ ] Add a Colleague to Help Manage Responses

SETTINGS
- [ ] Branding
- [ ] Data Classification
- [ ] Administrative Purpose
- [ ] Open / Close Form
- [ ] Delete Form

PERIPHERALS (Additional Forms and Notices)
- Support Forms
- Service Level Agreement (SLA)
- Terms of Use (ToU)

**Comment by Abi-Nada** [comment]
Only thing I found that's different from Prod is **when you try to delete a form**:

Even though this form was good to be deleted, it still gave me a toast error message and everything got very laggy and glitchy. The process in Prod is quite smooth compared to it:
Screenshot 2024-11-05 at 12 09 07 PM

**Comment by timarney** [comment]
🥇 Nice thanks for all the testing @Abi-Nada 

That's a solid list.

**Review by thiessenp-cds — COMMENTED** [review]
I was able to `yarn install` this without any errors. I tried the happy paths of publishing and viewing and managing a form. 

Skimming through the files, the only thing that stood were these lines. I'm assuming these are just future TODOs.
`@ts-expect-error ...`

From my end, looks good to me :)

**Comment by timarney** [comment]
@thiessenp-cds yes @ts-expect-error  we already have existing ones but yes didn't want to add noise to this PR fixing all the things and ending up with a bunch of conflicts.

**Review by dsamojlenko — APPROVED** [review]

**Pull request merged**
