### PR TITLE
chore: Typography improvements and cleanup

### PR DESCRIPTION
**Pull request by dsamojlenko**
# Summary | Résumé

Typography improvements:
- Correct font rendering
- More consistent styling for headings
- Remove/replace custom classes in favour of Tailwind defaults where possible

Adds a Typography page to help visualize default typography options: https://pyxb7mcnfu32vsio6udq72jun40whmqq.lambda-url.ca-central-1.on.aws/admin/typography

### CODE REVIEW

**Comment by timarney** [comment]
@dsamojlenko Looking good overall -- dropped you a couple of small notes via Slack.

@samsadasivan I'll look to you on this one for approval once you've had a chance to fully review on the staging URL.

**Comment by timarney** [comment]
Found this interesting so thought I would add as a comment here ... just some info about "noto"

https://www.youtube.com/watch?v=AAzvk9HSi84



Screenshot 2023-09-26 at 10 20 55 AM


Screenshot 2023-09-26 at 10 21 43 AM

**Review by samsadasivan — APPROVED** [review]
This all looks amazing! Super happy. This was hard work, so I am very appreciative

**Review by timarney — APPROVED** [review]
🥇

**Pull request merged**
