### PR TITLE
Adds comments noting apis no longer used

### PR DESCRIPTION
**Pull request by thiessenp-cds**
# Summary | Résumé

Comments unused apis

### CODE REVIEW

**Comment by craigzour** [comment]
I wonder if we should not just delete them to be honest. What do you think @bryan-robitaille ? 
No matter what we would have to rewrite them in order to use the new way APIs are defined.

**Comment by bryan-robitaille** [comment]
> I wonder if we should not just delete them to be honest. What do you think @bryan-robitaille ? No matter what we would have to rewrite them in order to use the new way APIs are defined.

Let's note it and create an issue for a follow up PR after the big merge.  The scope is rather large where we'll want to ensure that we remove not only the endpoints but all components that were also unique to that functionality.  We'd also need a DB migration to drop the API Users table and associated referenced fields.

**Comment by craigzour** [comment]
> > I wonder if we should not just delete them to be honest. What do you think @bryan-robitaille ? No matter what we would have to rewrite them in order to use the new way APIs are defined.
> 
> Let's note it and create an issue for a follow up PR after the big merge. The scope is rather large where we'll want to ensure that we remove not only the endpoints but all components that were also unique to that functionality. We'd also need a DB migration to drop the API Users table and associated referenced fields.

Sounds good! I will create a ticket. cc @thiessenp-cds

**Review by craigzour — APPROVED** [review]

**Comment by bryan-robitaille** [comment]
API removed in PR #3503

**Pull request closed without merging**
