### PR TITLE
Checkbox input mis-aligned on multi-line label

### PR DESCRIPTION
**Pull request by bryan-robitaille**
# Summary | Résumé

The checkbox and radio input element were normally hidden behind the styled label-input except when a label spanned multiple lines.  This PR aligns the input element and the label element so that one is always hidden by the other.

# Visual Changes
| Before | After |
|:-----:|:------:|
|Screen Shot 2021-05-03 at 12 12 54 PM|Screen Shot 2021-05-03 at 12 15 49 PM|

### CODE REVIEW

**Comment by mcman12** [comment]
Check and it looks good. thanks Bryan

**Comment by brdunfield** [comment]
I'm not sure that the left -100% is necessary, as when I disable it I don't see the original issue replicated.

I'm hesitant to style it off the page, as any user without CSS enabled won't be able to see it (probably not a super common issue these days, but something to consider..)

**Comment by brdunfield** [comment]
On further reflection if they don't have CSS enabled it won't style off the page. It's monday

**Comment by brdunfield** [comment]
Not something that's related to what you're fixing in this PR, but the vertical alignment of the checkboxes when the text gets longer than a line or two looks funky to me
Screen Shot 2021-05-03 at 10 37 18 AM

**Review by brdunfield — APPROVED** [review]
LGTM. I think checkbox styling will need iteration eventually as per my other comments, but this PR does what it says it does! 🦑

**Review by brdunfield — APPROVED** [review]
I like this approach a lot better! The alignment looks much cleaner too. 🦑

**Pull request merged**
