### PR TITLE
Updates form-builder edit styles colour contrast

### PR DESCRIPTION
**Pull request by thiessenp-cds**
# Summary | Résumé

Updates the form-builder Edit colour contrast in a few areas related to the Add item feature.

| Before                                          | After                                        |
| ----------------------------------------------- | -------------------------------------------- |
| Screenshot 2023-10-03 at 9 39 34 AM | Screenshot 2023-10-03 at 9 39 43 AM |

### CODE REVIEW

**Comment by timarney** [comment]
Is the focused / active state supposed to be "blue on blue" ?

Screenshot 2023-10-03 at 10 26 59 AM

**Comment by thiessenp-cds** [comment]
> Is the focused / active state supposed to be "blue on blue" ?
> 
> Screenshot 2023-10-03 at 10 26 59 AM

I think that's the active state for the focussed items. But now I wonder :) @samsadasivan does this look right?

**Comment by thiessenp-cds** [comment]
> > Is the focused / active state supposed to be "blue on blue" ?
> > Screenshot 2023-10-03 at 10 26 59 AM
> 
> I think that's the active state for the focussed items. But now I wonder :) @samsadasivan does this look right?

Here is an updated button (thanks @samsadasivan for the help)
Screenshot 2023-10-03 at 11 22 46 AM

I moved some styles around so that sm/tablet is the default and laptop is the responsive size class.

Another minor issue/question. I noticed the right border on the inputs is not being rounded. It's odd because I only see a general border being set (so top/right/bot..). Is there anything else that you can think of that might not be that obvious? (or maybe this is a "just me/my device" thing.. :)

**Comment by timarney** [comment]
Press and hold is still an issue.

press-hold

**Comment by thiessenp-cds** [comment]
> Press and hold is still an issue.
> 
> press-hold [ press-hold ](https://user-images.githubusercontent.com/62242/272353075-e80009bf-2057-4646-8e65-7f1b633b6712.gif) [ ](https://user-images.githubusercontent.com/62242/272353075-e80009bf-2057-4646-8e65-7f1b633b6712.gif)

Good find! I completely missed that while I was too focussed on keyboard interaction. How's this?
Screenshot 2023-10-03 at 2 06 32 PM

**Review by timarney — APPROVED** [review]

**Pull request merged**
