### PR TITLE
Focus feedback from Julianna and Eric

### PR DESCRIPTION
**Pull request by nmakuch**
## This PR consists of the following:

I wasn't happy with some inconsistencies in the focus states for the forms components and submit button, but after some discussion with Eric and some feedback from Julianna I've made some updates with their help.

The changes are as follows:

### One consistent focus colour
- Links previously had a separate focus colour but have been updated along with the form inputs to have one darker shade of blue that I was previously using for active states in my previous PR briefly.

### Updating the buttons to have a small outline
- Worried the colour switch alone won't be enough for visually impaired users
- The buttons have been updated to have a small solid white box shadow (in the case this button is ever applied to a darker background), followed by a 2 px blue outline to stand out more.

### CODE REVIEW

**Comment by brdunfield** [comment]
This looks pretty good to me. My only worry is that the blue is dark enough that it might be difficult to distinguish it from the black non focussed elements? Particularly in a radio or checkbox situation? Was that already discussed with Eric / Julianna?

I really like the button outline change!

**Comment by nmakuch** [comment]
> This looks pretty good to me. My only worry is that the blue is dark enough that it might be difficult to distinguish it from the black non focussed elements? Particularly in a radio or checkbox situation? Was that already discussed with Eric / Julianna?
> 
> I really like the button outline change!

It was, but they haven't seen it live, I've actually just sent them the heroku link to check out so I'll make sure to get the OK from them before doing anything

**Review by brdunfield — APPROVED** [review]
Perfect! Well LGTM codewise, so once you have the approval on the colour you're good to go 👍

**Comment by nmakuch** [comment]
> Perfect! Well LGTM codewise, so once you have the approval on the colour you're good to go 👍

Sounds good :D Thanks Bethany!

**Pull request merged**
