### PR TITLE
Account permissions

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Fixes: https://github.com/cds-snc/platform-forms-client/issues/2341

Updates manage permissions page
- Updates Page name / user name (email) stying
- Adds success / fail message when saving
- Replaces buttons with a toggle switch
- Adds back to accounts link (replaces left nav)

 
Screenshot 2023-06-29 at 1 32 57 PM

Screenshot 2023-06-29 at 1 21 36 PM

# Test instructions | Instructions pour tester la modification

- From the permissions screen test toggling on / off permissions  
- Ensure permissions end up in the correct state for on / off. 

Sequential steps (1., 2., 3., ...) that describe how to test this change. You should include
anything outside the README that will help the developer access your changes and be able to test
them such as any environmental setup steps and/or any time-based elements that this requires.
This will help a developer test things out without too much detective work.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

Are there any related issues or tangent features you consider out of scope for
this issue that could be addressed in the future? If so please create issues and provide
links in this section

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by connorscarolyns** [comment]
Can we make the off-state a different colour? I apologize for not adding this to the design.
image

**Comment by connorscarolyns** [comment]
The spacing between headings is too tight; add mb-12 to the bottom of UL lists:
 
image

**Comment by timarney** [comment]
Thanks @connorscarolyns 

@thiessenp-cds is working on some a11y for the toggles after that I'll pick this back up and work on the design fixes.

**Comment by timarney** [comment]
Opened a new issue for the "overall" layout https://github.com/cds-snc/platform-forms-client/issues/2351

**Comment by timarney** [comment]
> The cancel button is missing. Was this intentional?

Added the cancel button

https://github.com/cds-snc/platform-forms-client/pull/2342/commits/848901916ac4982ed47b5bd4cc94965ecf5c6581

**Comment by timarney** [comment]
> The spacing between headings is too tight; add mb-12 to the bottom of UL lists:
Added spacing:
https://github.com/cds-snc/platform-forms-client/pull/2342/commits/c32c1f612c6e37318b40ce2545c4d1081cfa5ded

**Comment by timarney** [comment]
> Can we break the name and email into two lines?

Yes - updated to:
Screenshot 2023-06-29 at 1 05 18 PM

**Comment by timarney** [comment]
https://github.com/cds-snc/platform-forms-client/pull/2342#issuecomment-1613356098

-- updated toggle colours + swap the toggle on / off labels

**Comment by thiessenp-cds** [comment]
Nice work, LGTM :)
(I couldn't find the option to approve but consider it approved :)

**Review by thiessenp-cds — APPROVED** [review]
Never mind, found it. LGTM :)

**Pull request merged**
