### PR TITLE
fix: form name not being set when title is set

### PR DESCRIPTION
**Pull request by daine**
# Summary | Résumé
Fixes
- #2157 
- #2019 

# Scope
This PR is an attempt to fix some usability issues with form names and titles, specifically about:
- #2157 
- The main issue here is that there is an attempt in the code to use the titles as the form name, but the usability is a little confusing. The fix is to have clear separation of form names to titles, as well as have the name automatically filled with the title when the user clicks on the name field.
- #2019 
- This PR gives the ability to save a form without a name. By default, it shows up as an "Unnamed form file". The user is still able to set and see titles when viewing their forms list.

# UI Changes
| Before                                          | After                                        |
| ----------------------------------------------- | -------------------------------------------- |
| Forms with a title but no name | Forms with a title but no name |
|Screenshot 2023-06-19 at 3 43 17 PM|Screenshot 2023-06-19 at 3 41 41 PM|
| Forms with no title and no name | Forms with no title and no name |
|Screenshot 2023-06-19 at 4 15 05 PM|Screenshot 2023-06-19 at 4 18 15 PM|

## More UI Changes

Creating a form with form titles (in french and english) but **without a name**
Form Titles No Name

Attempting to share a form without a name, which lets the user click on the "name your form". This puts the focus on the form name field, which triggers the autocomplete
Autoname Form With Title

Autocomplete for the name, while in french editing mode
Autoname form with french title

If we don't want to name the form at all, we can leave it blank
Removing Form Name

# Test instructions | Instructions pour tester la modification
**Here are the different scenarios to test this functionality:**
```
1. Create a new form or import a form file
2. Set a title
3. Click on "Unnamed form file" (the input field for the form name)
4. Form name should autopopulate with your title
```
```
1. Create a new form or import a form file
2. Set a title
3. Attempt to share a form
4. Click on "name your form"
6. Form name should autopopulate with your title
```
```
1. Go to "My Forms"
2. You should see both the form name and form title
```
```
1. Create a new form or import a form file
2. Don't set a form name, or clear the form name & save
3. Go to "My Forms"
4. You should see "Unnamed form file" and form title beneath it
```

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet
Pending approval ✅ from the designers and previous code contributors
@anikbrazeau @timarney 
@samsadasivan @connorscarolyns 

## Some assumptions
Form name is the name of the specific form file or documention. It is not a required, unique identifier.
Form names are separate from titles, and should also be set separately.
Form names are a requirement when sharing a form (this is the current status, but this requirement should be revisited)

## ⚠️ Form names and titles behaviours have changed in this PR
**A form name will automatically be applied in this specific scenario:**
A user types in a form title, either in french or english.
A user clicks on the form name field.
The form name field gets autopopulated with title (in the current language they're editing).
The autopopulated form field text is also highlighted. Once they start typing, it will allow the user to quickly overwrite it or delete it entirely.

A user types in a form title, either in french or english
A user attempts to share a form and clicks on the "name your form" link
The form name field gets autopopulated with title (in the current language they're editing).
The autopopulated form field text is also highlighted. Once they start typing, it will allow the user to quickly overwrite it or delete it entirely.

**A form name will NOT be automatically applied in these scenarios**
A user types in a form title, either in french or english
User navigates away from the page

A user types in a form title, either in french or english
A user attempts to share a form and does not click on the "name your form" link

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by connorscarolyns** [comment]
This is excellent work! 
I love the functionality; I have one comment, which may be out of scope for this work.

1. I found it confusing for the save button to appear and disappear based on if I had a form title. It took me a while to figure out why it was displayed sometimes and not others. It would be better to have the button on the screen at all times and let users know what conditions must be met before they can save.

**Review by thiessenp-cds — APPROVED** [review]
Nice work! LGTM :)

May want to leave open for Tim/Dave to comment

**Comment by timarney** [comment]
> I found it confusing for the save button to appear and disappear based on if I had a form title. It took me a while to figure out why it was displayed sometimes and not others. It would be better to have the button on the screen at all times and let users know what conditions must be met before they can save.

@connorscarolyns wondering your thoughts on removing that button all together at this point in a follow-up PR.  In most cases we auto-save on page navigation now.

**Comment by connorscarolyns** [comment]
> In most cases we auto-save on page navigation now.
In this instance, the form is not saved when moving from the form to your forms.

**Comment by daine** [comment]
@timarney @connorscarolyns I [created an issue](https://github.com/cds-snc/platform-forms-client/issues/2314) regarding the saving mechanism. Curious about removing the button too, but I also ran into the same thing where it didn't auto-save when I modified the form names and titles (when testing for this PR)

**Comment by timarney** [comment]
I seem to be getting an issue when I swap to FR in my forms

- Filled out form name (not form file name)

Screenshot 2023-06-20 at 12 59 43 PM

**Comment by daine** [comment]
> I seem to be getting an issue when I swap to FR in my forms
> 
> * Filled out form name (not form file name)
> 
> Screenshot 2023-06-20 at 12 59 43 PM

Great catch. There shall be no p's within p's! Fixed.

**Review by timarney — APPROVED** [review]
Nice work.

**Pull request merged**
