### PR TITLE
userHasSecurityQuestions property implementation

### PR DESCRIPTION
**Pull request by bryan-robitaille**
# Summary | Résumé

Modifies previous logic that added security questions array to the session.  

Replaced with:
- new property on the session that holds a boolean for `userHasSecurityQuestions`
- Once property is set to 'true' no more checks will occur during that session.

Chore:
- moved the `acceptableUseCache` module to `cache` folder
- modified new Cypress command to provide different answers for different questions to ensure proper future testing.

# Test instructions | Instructions pour tester la modification
- Existing tests should pass

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by timarney** [comment]
Looks like the profile page was missed.

Screenshot 2023-08-08 at 3 27 24 PM

**Comment by bryan-robitaille** [comment]
> Looks like the profile page was missed.

Fixed

**Comment by timarney** [comment]
Just a couple of outstanding lint issues 

Screenshot 2023-08-08 at 3 56 04 PM

**Comment by bryan-robitaille** [comment]
> Just a couple of outstanding lint issues

🤦  right... 
Fixed... for good this time.

**Review by timarney — APPROVED** [review]
🎉

**Pull request merged**
