### PR TITLE
feature: GC Forms adminstrators can access API settings

### PR DESCRIPTION
**Pull request by bryan-robitaille**
# Summary | Résumé
This PR removes the "zitadelAuth" flag and instead does a privilege check in order to enable API Prototype testing in Production.

| Before                                          | After                                        |
| ----------------------------------------------- | -------------------------------------------- |
| Only available if "zitadelAuth" flag was active | User must be an owner of the form, including manage all forms, and have "View" "Flag" privilege (useIsAdminUser) |

# Test instructions | Instructions pour tester la modification
With Manage All Forms and "View Flag" privilege you should be able to:
- View Settings API page,
- Create key,
- Refresh Key
- Delete Key

Without Manage All Forms or "View Flag" privilege you should NOT be able to:
- View Settings API page,
- Create key,
- Refresh Key
- Delete Key

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet
There is a small risk that a user who is the form owner but does not have "View Flag" could create, refresh, or delete a key.  Since this user is still the form owner and no data can be cross contaminated the impact is small.  In a nutshell a form owner who is really really savvy and dedicated could access the preview feature of the API to manage their own form responses before the feature is fully public.

Accepting this risk and impact reduces the amount of code and privileges checks that would need to be changed before going public, or widening the scope of the testing pool.

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by craigzour** [comment]
@bryan-robitaille Will continue testing it tomorrow morning but I got stopped by what feels like a bug (could not figure out why yet). When I have form ownership and the view flag permission I can see the API Access tab but when I click on it I get redirected to `http://localhost:3000/en/form-builder/cm05mxdua0003moy60gc0cp8n/settings`

**Comment by bryan-robitaille** [comment]
> When I have form ownership and the view flag permission I can see the API Access tab but when I click on it I get redirected to `http://localhost:3000/en/form-builder/cm05mxdua0003moy60gc0cp8n/settings`

@craigzour try doing a manual refresh of the page.  I ran into the same issue with the navigation not updating in real time with the privilege changes.  It would seem once it's cached it is not recomputed unless a hard refresh of the page is done.
To access the API Settings page, clicking on the link and not being redirect to settings, you'll need Manage All Forms privilege.

**Comment by craigzour** [comment]
> > When I have form ownership and the view flag permission I can see the API Access tab but when I click on it I get redirected to `http://localhost:3000/en/form-builder/cm05mxdua0003moy60gc0cp8n/settings`
> 
> @craigzour try doing a manual refresh of the page. I ran into the same issue with the navigation not updating in real time with the privilege changes. It would seem once it's cached it is not recomputed unless a hard refresh of the page is done. To access the API Settings page, clicking on the link and not being redirect to settings, you'll need Manage All Forms privilege. I missed that in my testing steps.... sorry.

It works ;) I noticed one small thing (not a big deal) when you try to manually access the API Access view with no permission. I get the following error message for a second and then I get redirected to the `/settings` page.
Screenshot 2024-09-24 at 8 38 59 AM

**Review by craigzour — APPROVED** [review]
LGTM :)

**Pull request merged**
