### PR TITLE
chore: update preview header

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Updates the preview FIP header to bring it back inline with the current front facing output 
Screenshot 2023-09-27 at 9 47 46 AM

# Test instructions | Instructions pour tester la modification

- Test preview output of a form under the form builder tool

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by connorscarolyns** [comment]
nice!

**Review by thiessenp-cds — COMMENTED** [review]
It looks like the header may need updating for small screens (similar to another PR). BUT is the design to have the content and header line up? (looking through figma now)


Screenshot 2023-09-27 at 10 11 19 AM

**Comment by timarney** [comment]
> It looks like the header may need updating for small screens (similar to another PR). BUT is the design to have the content and header line up? (looking through figma now)

Ya let's look to merge this one and I'll pick up the public facing content on this other PR

https://github.com/cds-snc/platform-forms-client/pull/2721/commits/6e9fcb481aa5aed23c1319f075ee823a0052ff91

**Review by thiessenp-cds — APPROVED** [review]
LGTM :)

**Pull request merged**
