### PR TITLE
build: fix staging-deploy Github action

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

- Trying to fix a recurring issue we have with our staging deployment script. @patheard suggested a new way of waiting for an action to complete before triggering another one.

### CODE REVIEW

**Review by patheard — CHANGES_REQUESTED** [review]
Just two minor tweaks from my end.  

1. There are a few spots in this workflow where `${{ github.sha }}` is referenced.  Since this workflow is now being triggered by another workflow being complete, I think it would be safer to use the [`workflow_run` payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run) to get that SHA: 
```
${{ github.event.workflow_run.head_sha }}
```

2. If you wanted, you could also add a check to fail early if the `push-staging` workflow fails, rather than trying to deploy the failed image push.  A simple example would be just to add a `on-failure` job to the workflow:
```yaml
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
   
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
```

**Comment by craigzour** [comment]
> ```yaml
> on-failure
> ```

Gotcha! Just a question about your second point. How would the `staging-deploy` action not be fully executed just because we have this `on-failure` step? How does it work?

**Comment by patheard** [comment]
> Gotcha! Just a question about your second point. How would the `staging-deploy` action not be fully executed just because we have this `on-failure` step? How does it work? cc @patheard

This would be to catch cases like what happened yesterday where the `push-staging` job timed out and failed.  In that case, you wouldn't want to try to run `staging-deploy` to deploy a new image (since it wouldn't exist).

In the `on-failure` job, you could do something like [use a Slack webhook](https://github.com/cds-snc/notification-terraform/blob/main/.github/workflows/merge_to_main_staging.yml#L127-L131) to post back to the `#forms-dev` channel to alert people that the deploy job didn't work as expected.

**Comment by craigzour** [comment]
> > Gotcha! Just a question about your second point. How would the `staging-deploy` action not be fully executed just because we have this `on-failure` step? How does it work? cc @patheard
> 
> This would be to catch cases like what happened yesterday where the `push-staging` job timed out and failed. In that case, you wouldn't want to try to run `staging-deploy` to deploy a new image (since it wouldn't exist).
> 
> In the `on-failure` job, you could do something like [use a Slack webhook](https://github.com/cds-snc/notification-terraform/blob/main/.github/workflows/merge_to_main_staging.yml#L127-L131) to post back to the `#forms-dev` channel to alert people that the deploy job didn't work as expected.

Oh ok so we would add those two "steps" in the `staging-build-push-container` action then? The run command  with the `echo` will be what triggers or not the execution of the `staging-deploy` action?

**Comment by patheard** [comment]
I'd been thinking more that you could add them to the `.github/workflows/staging-deploy.yml` workflow like so:

```yaml
name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Staging — Push container to ECR"]
    types:
      - completed

jobs:
  # This job will only trigger if the staging-build-push-container workflow is unsuccessful.
  # It will post a message to Slack to notify the team there was a problem. 
  # You'll need a `FORMS_DEV_SLACK_WEBHOOK` GitHub secret that can post to the #forms-dev channel to set this up.
  unable-to-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Unable to deploy Staging form viewer: <https://github.com/cds-snc/platform-forms-clients/actions/workflows/staging-build-push-container.yml|ECR push failed>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.FORMS_DEV_SLACK_WEBHOOK }} 
          exit 1

  # If staging-build-push-container was successful, proceed with the deployment.
  deploy-form-viewer-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    # remaining deploy steps

```
Happy to chat more tomorrow if you've still got questions.

**Comment by craigzour** [comment]
> I'd been thinking more that you could add them to the `.github/workflows/staging-deploy.yml` workflow like so:
> 
> ```yaml
> name: Deploy to Staging
> 
> on:
>   workflow_run:
>     workflows: ["Staging — Push container to ECR"]
>     types:
>       - completed
> 
> jobs:
>   # This job will only trigger if the staging-build-push-container workflow is unsuccessful.
>   # It will post a message to Slack to notify the team there was a problem. 
>   # You'll need a `FORMS_DEV_SLACK_WEBHOOK` GitHub secret that can post to the #forms-dev channel to set this up.
>   unable-to-deploy:
>     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
>     runs-on: ubuntu-latest
>     steps:
>       - name: Post to Slack
>         run: |
>           json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Unable to deploy Staging form viewer: <https://github.com/cds-snc/platform-forms-clients/actions/workflows/staging-build-push-container.yml|ECR push failed>"}}]}'
>           curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.FORMS_DEV_SLACK_WEBHOOK }} 
>           exit 1
> 
>   # If staging-build-push-container was successful, proceed with the deployment.
>   deploy-form-viewer-service:
>     if: ${{ github.event.workflow_run.conclusion == 'success' }}
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> 
>     # remaining deploy steps
> ```
> 
> Happy to chat more tomorrow if you've still got questions.

Got it now! Stil need to Github actions and I got mixed up by the `job` aspect vs the `step` one. Going to update the PR soon. Thanks :)

**Comment by craigzour** [comment]
@patheard  New Slack secret has been added here https://github.com/cds-snc/platform-forms-client/settings/secrets/actions

**Pull request merged**
