### PR TITLE
[WIP] Show admin navigation on authenticated pages

### PR DESCRIPTION
**Pull request by fitore-cds**
# Summary | Résumé

- This is the first iteration of a basic admin navigation that appears below the FIP if the user is authenticated
- The `Base` component will receive `user` as a prop, if it's on an authenticated page

### CODE REVIEW

**Comment by brdunfield** [comment]
It doesn't seem like Logging out works for me? (Tested locally)

**Comment by fitore-cds** [comment]
@brdunfield Thank you, I fixed the "Logout" in the nav - turns out I couldn't rely on the `Link` component so switched it to a `button`. Will leave it with Nick to improve :-)

**Comment by brdunfield** [comment]
The PR review app seems to not have built properly.. /welcome-bienvenue is totally broken. But it works locally so I'm not too concerned. 🤔

**Review by brdunfield — APPROVED** [review]
This looks great! Thanks Fitore! 🦑

**Pull request merged**
