### PR TITLE
* Update and add learn more administrative purposes box.

### LINKED ISSUE #3750: UI fixes to Settings Page
## Description

Figma File: https://www.figma.com/design/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?node-id=3059-910&t=FLExykdEc8JWIkHF-0 

- [x] Purple help text is currently under "Data Classification" heading, when it should be under the "Settings" heading
- [x] Help text in incorrect it should read "These settings can only be changed before publishing." "Ces paramètres ne peuvent être modifiés qu’avant la publication."
- [x] Spacing is inconsistent and too cramped between each section: Data classification, Response delivery option, Purpose and use. Ensure there is a class of "mb-10" between each section.
- [x] text correction: Response delivery option should be "Delivery option" "Option de livraison"
- [x] text correction: "Retrieve responses within 45 days." should be "GC Forms holds data temporarily for 30 days." "Formulaires GC conserve les données temporairement pour 30 hours."
- [x] Bold the line "Help us understand how form responses will be used"
- [x] Italics "Administrative purposes," "Non-administrative purposes,"
- [x] Alignment of bullets "Personal information used to make a decision about an individual" and hint text is misaligned, try class "ml-12"
- [x] Help text for choosing a delivery option is missing
- [x] Help text for Administrative purposes reflects information for choosing a delivery option (the current info here should be for the missing help text in the point above^^)

## Steps to reproduce
1. Go to Staging -> the Settings page
2. Observe above flags

## Expected behaviour
Figma file: https://www.figma.com/design/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?node-id=3059-910&t=FLExykdEc8JWIkHF-0

## Screenshots or videos
Currently in Staging:

### LINKED ISSUE #3753: Settings page: missing help text for choosing a delivery option
### Description:

Help text for choosing a delivery option is missing.

Figma file: https://www.figma.com/design/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?node-id=3059-928&t=05IEnua25tISiWGR-0

### Acceptance Criteria:
- [ ] Create help text
- [ ] Add content

### LINKED ISSUE #3754: Settings page: Update content in "Purpose and Use" help text
### Description:

The content in "Learn more about administrative purposes" is reflecting the incorrect text.

Figma file: https://www.figma.com/design/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?node-id=3059-929&t=05IEnua25tISiWGR-0

Acceptance Criteria:
- [ ] Content is updated to reflect designs

### PR DESCRIPTION
**Pull request by ShadeWyrm**
Closes #3753 &  
Closes #3754 
--
Closes #3750

* Italics "Administrative purposes," "Non-administrative purposes,"
*  Help text for choosing a delivery option is missing
*  Help text for Administrative purposes reflects information for choosing a delivery option (the current info here should be for the missing help text in the point above^^)

### CODE REVIEW

**Comment by anikbrazeau** [comment]
## Rename pill under "Settings" to "Responses" to correspond with expanded scope beyond response delivery

### Previously:
EN: `Response delivery`
FR: `Livraison des réponses`
Screenshot 2024-06-06 at 2 39 06 PM
Screenshot 2024-06-06 at 2 39 26 PM

### Suggested adjustment:
EN: `Responses`
FR: `Réponses`
Screenshot 2024-06-06 at 2 39 02 PM
Screenshot 2024-06-06 at 2 39 15 PM

### Rationale
Delivery option is the next structural level 
Level 1 Settings 
Level 2 Responses / Branding / Form management
Level 3 Data classification / Delivery options / Purpose and use

**Comment by anikbrazeau** [comment]
## Suggested change: Save button for each setting or for all settings

Currently, `Delivery option` and `Purpose and use` have save buttons but `Data classification` does not
Screenshot 2024-06-06 at 2 45 28 PM

**Comment by anikbrazeau** [comment]
## Suggested tweaks to administrative purpose modal

### Italicize "Privacy Act"

## Open links in new tab
Screenshot 2024-06-06 at 2 54 25 PM

**Comment by anikbrazeau** [comment]
## Suggested tweaks to publish page

### Match setting name with heading from settings in French
"Usage prévu" not "Objectif et utilisation"

Screenshot 2024-06-06 at 3 13 46 PM

### Add a space before colon in French

Screenshot 2024-06-06 at 3 13 27 PM


### Capitalize the first letter of each setting in French
"Pas définis"
"Fins administratives"
"Fin non-administratives"

Screenshot 2024-06-06 at 3 15 03 PM

Screenshot 2024-06-06 at 3 14 35 PM

Screenshot 2024-06-06 at 3 14 18 PM

**Comment by anikbrazeau** [comment]
## It's currently possible to publish without completing settings requirements

The publish button was previously not there until all requirements were complete

Screenshot 2024-06-06 at 3 19 16 PM

Screenshot 2024-06-06 at 3 19 23 PM

**Comment by anikbrazeau** [comment]
## Suggested change: Remove banner from "Form management" pill since these settings (Open/Close) can be modified post-publishing

Screenshot 2024-06-06 at 3 21 00 PM

Screenshot 2024-06-06 at 3 21 09 PM

**Comment by anikbrazeau** [comment]
Not sure if it's related so logged it separately, but as I was testing also encountered: https://github.com/cds-snc/platform-forms-client/issues/3761

**Comment by anikbrazeau** [comment]
## Suggested change: Remove "(default)"  / "(par défault) from dropdowns for classification (in settings and in edit)

Previously, when it was not a requirement for settings, "Protected A (default)" was the option that showed, if you change to "Unclassified" or "Protected B" it still says PA is default which is a bit strange in terms of experience.
 
Screenshot 2024-06-06 at 2 55 56 PM

**Review by timarney — APPROVED** [review]

**Pull request merged**
