### PR TITLE
refactor: More explcity privilege checks

### PR DESCRIPTION
**Pull request by bryan-robitaille**
# Summary | Résumé

Add more explicit privilege checks where `checkPrivilege` functions are used.

We often don't pass in the `object: {}` which ensures that only users that have global permissions can access that particular function.  The base function now treats all checks that don't include an object as a global permissions check.

# Test instructions | Instructions pour tester la modification

App should work as normal.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

This does not include going through each `lib` to ensure that all CRUD functions leverage proper ability checks.

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Review by craigzour — DISMISSED** [review]
LGTM!

**Comment by timarney** [comment]
Couple of notes for the future 

- Passing {} called object is confusing :)
- It would be nice if we could default the {} so we don't have to pass it ... outside of the comment you can't just look at the code and understand it for "all"

**Comment by bryan-robitaille** [comment]
> Couple of notes for the future
> 
>     * Passing {} called object is confusing :)
> 
>     * It would be nice if we could default the {} so we don't have to pass it ... outside of the comment you can't just look at the code and understand it's for "all"

That's a great suggestion. We'll have to rework the whole permission set when we start exploring teams later this year but for now I've modified the privilege check to check the global permission if no specific object is passed in.

**Review by timarney — APPROVED** [review]
🥇

**Pull request merged**
