### PR TITLE
refactor: remove custom gc-headers

### LINKED ISSUE #902: Remove `gc-h1`, `gc-h2`, `gc-h3` classes.
Using custom classes for `gc-h1`, `gc-h2`, and `gc-h3` is unnecessary. Tailwind styles can be applied for <h1>, <h2>, and <h3> tags.

### PR DESCRIPTION
**Pull request by jeberhardt**
# Summary | Résumé

Closes #902 

The use of custom headers, in the form of `gc-h1`, `gc-h2`, and `gc-h3` was unnecessary.  All corresponding styles are now being applied directly to the `h1`, `h2`, and `h3` tags, respectively.

I also removed the <Heading> component, as it was not being used anywhere in the application.

# Test instructions | Instructions pour tester la modification

Loading the website, all headers should appear the same as they always have.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

There was one instance where a `h2` tag was styled as an `h3` tag, in the `Alert` component. This is now being re-styled as `h2`, which does increase the font a tiny bit, but also keeps the semantic meaning. I do not think this is of any concern, and that the slightly larger font is acceptable.

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [x] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Comment by craigzour** [comment]
@jeberhardt Found a few places where the text size/style has changed with your PR (compared to staging)

| Before                                          | After                                        |
| ----------------------------------------------- | -------------------------------------------- |
| Screen Shot 2022-08-18 at 9 13 04 AM | Screen Shot 2022-08-18 at 9 27 58 AM |
| Screen Shot 2022-08-18 at 9 13 32 AM | Screen Shot 2022-08-18 at 9 28 07 AM |
| Screen Shot 2022-08-18 at 9 15 48 AM | Screen Shot 2022-08-18 at 9 28 20 AM |
| Screen Shot 2022-08-18 at 9 15 33 AM | Screen Shot 2022-08-18 at 9 28 25 AM |

**Review by craigzour — CHANGES_REQUESTED** [review]
See my comment about noticeable style changes

**Comment by jeberhardt** [comment]
@craigzour - Thanks! It seems that there were a few places where there were `h2` elements that didn't already have the `gc-h2` class added to them. So when I added that styling to all of the `h2` elements, some elements got new styling.

**Comment by jeberhardt** [comment]
> > @craigzour - Thanks! It seems that there were a few places where there were `h2` elements that didn't already have the `gc-h2` class added to them. So when I added that styling to all of the `h2` elements, some elements got new styling.
> 
> @jeberhardt Are we planning on making adjustments or not? I see no changes so just wanted to make sure what is our next step on this PR.

@craigzour - Yes, I meant to reply that I should follow up with @connorscarolyns. I think that all headers should have the same visual impact, and would like to get input from design before moving forward. I think it's ok that some of the font sizes have changed because of this PR, but want to make sure that people are aware of it.

**Comment by connorscarolyns** [comment]
> 
@craigzour Thank you for bringing this to my attention. While I'm sure that the style change will not break the product. There are cases where a different heading class has been purposefully applied to solve for a visual hierarchy problem. This is standard practice in many cases to maintain accessible headers while providing proper visual cues.  As I'm unsure if this was the case, I can't provide direction without a deeper look into what has changed.

**Review by craigzour — APPROVED** [review]

**Comment by jeberhardt** [comment]
@connorscarolyns - I think that in the 3 examples above that @craigzour pointed out, that none of those are actually headers.

"No responses for selected form" - This is more of an "alert" than it is a heading.
"Edit Form Config File:" - This is more of a label for the text area than it is a heading.
"Current Token:" - This is more of a label for the text area than it is a heading.

As for the other <h2> tag: "Log in with your CDS-SNC Google Account", I don't think this has any negative impact if it's slightly larger (30px instead of 26px). I also don't think this qualifies as "header" content, as it is primarily instructional in nature.

**Comment by connorscarolyns** [comment]
Reviewed with @jeberhardt . Everything looks fine, good to go.

**Review by connorscarolyns — APPROVED** [review]
Reviewed UI changes visually. Approved.

**Pull request merged**
