### PR TITLE
Adds unknown error to profile dialog plus loader

### PR DESCRIPTION
**Pull request by thiessenp-cds**
# Summary | Résumé

Adds an "unknown error" to the profile dialog. 

Also adds the start of a "loader" for the create security questions page. I was noticing a small delay, even locally, when submitting the form. Currently this just disables the submit button as an indicator when submitting.

## Future work

Consider a "submitting" (previously called "loading") pattern for all/most of our forms.

### CODE REVIEW

**Comment by samsadasivan** [comment]
Will start thinking of a "loading" pattern for forms

**Comment by timarney** [comment]
Thinking in a case where questions don't exist 

We should just display the error and not the form -- given you shouldn't be able to submit without questions.

Currently you can end up in this state.
Screenshot 2023-08-01 at 3 02 32 PM

**Comment by thiessenp-cds** [comment]
> Thinking in a case where questions don't exist
> 
> We should just display the error and not the form -- given you shouldn't be able to submit without questions.
> 
> Currently you can end up in this state. Screenshot 2023-08-01 at 3 02 32 PM

Good point. Instead, I'll have it show a dialog with just the title and error

**Comment by thiessenp-cds** [comment]
> > Thinking in a case where questions don't exist
> > We should just display the error and not the form -- given you shouldn't be able to submit without questions.
> > Currently you can end up in this state. Screenshot 2023-08-01 at 3 02 32 PM
> 
> Good point. Instead, I'll have it show a dialog with just the title and error
Screenshot 2023-08-01 at 3 21 29 PM

**Pull request merged**
