### PR TITLE
fix: Re-add provider for layout

### LINKED ISSUE #2628: Unable to delete a draft and published forms
Browser: Chrome
Device: Mac

I get an error message when I try to delete a draft and a published form.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc042IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8a0bad2955fe5d8effe3c55c4e994bee53afb86e/image.png)

### PR DESCRIPTION
**Pull request by timarney**
# Summary | Résumé

Fixes #2628

Wraps the Two Column layout with Template provider.

# Test instructions | Instructions pour tester la modification

- Visit my forms
- Delete an existing form

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

### CODE REVIEW

**Review by bryan-robitaille — DISMISSED** [review]
Tested and I was able to delete a form

**Review by thiessenp-cds — COMMENTED** [review]
Did a quick test also and was able to delete a form.
I tried creating a new form and it seems like some state is lost when saving a draft and then opening it again in Edit mode. If this doesn't happen for you must just be a local thing for me.

**Comment by timarney** [comment]
@thiessenp-cds can you re-create on the preview url ?
https://moj6j7otdcrzci3s4xualurfhi0bpbpl.lambda-url.ca-central-1.on.aws/

**Review by dsamojlenko — DISMISSED** [review]

**Comment by thiessenp-cds** [comment]
> @thiessenp-cds can you re-create on the preview url ? https://moj6j7otdcrzci3s4xualurfhi0bpbpl.lambda-url.ca-central-1.on.aws/

This could also be because of my roundabout way of creating a form :)

https://github.com/cds-snc/platform-forms-client/assets/107579368/b5e1885a-ce75-40ab-ac86-48770e2fe3c6

**Comment by timarney** [comment]
@thiessenp-cds thanks for the recording I suggest we look into that separately as it's more around saving vs fixing the delete.

**Comment by timarney** [comment]
@thiessenp-cds based on a failing cypress tests we moved the provider out of the layout itself and higher up into the getLayout function.

**Comment by thiessenp-cds** [comment]
> https://moj6j7otdcrzci3s4xualurfhi0bpbpl.lambda-url.ca-central-1.on.aws/

Nice work! Can confirm create/save/edit/delete works as expected

**Pull request merged**
